# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1872086dc39571c2af1567f9fbdae8b4e61a977e534d80240b9e5743088ec0b2102bb7a9335d033bb3636521c8041534fe5b6946a49634fd91720b0b0e7e7ea6

test:
  secret_key_base: 880c903c6ef9730d1fb1dc1534a05d0487a338425f201861ae68788e750016e0ed0348b3749838446a3105079e55e1a244ff26be1fe60b3001a8adf1250362d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
